//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models.EFConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Edificio
    {
        public int ID_Edificio { get; set; }
        public string Edi_Ciudad { get; set; }
        public string Edi_Municipio { get; set; }
        public string Edi_Direccion { get; set; }
        public string Edi_Nombre { get; set; }
        public Nullable<int> Edi_Proyecto { get; set; }
        public Nullable<int> Edi_SubProyecto { get; set; }
        public Nullable<int> Edi_Num_Emp_Armados { get; set; }
        public Nullable<int> Edi_Num_Emp_Desarmados { get; set; }
    }
}
