//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models.EFConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ServicioA
    {
        public int Id { get; set; }
        public Nullable<int> Servicio { get; set; }
        public string Enlace { get; set; }
        public string Coordinador { get; set; }
        public string Supervisor { get; set; }
        public string Ubicacion { get; set; }
        public string Edificio { get; set; }
        public Nullable<int> Desarmados { get; set; }
        public Nullable<int> Armados { get; set; }
        public Nullable<int> Turno { get; set; }
        public string Region { get; set; }
        public string Dias { get; set; }
        public Nullable<int> Jornada { get; set; }
        public Nullable<int> CubreDescansos { get; set; }
        public Nullable<int> CubreFaltas { get; set; }
        public string Gerente { get; set; }
        public Nullable<int> CubreDescansosD { get; set; }
        public Nullable<int> CubreFaltasD { get; set; }
        public string Ruta { get; set; }
        public Nullable<int> JT { get; set; }
        public Nullable<int> JS { get; set; }
        public Nullable<decimal> Sa { get; set; }
        public Nullable<decimal> Sd { get; set; }
        public Nullable<decimal> Sjs { get; set; }
        public Nullable<decimal> Sjt { get; set; }
    }
}
