//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models.EFConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SIM
    {
        public int ID_Sim { get; set; }
        public string Sim_Codigo { get; set; }
        public string Sim_Numero { get; set; }
        public string Sim_Companhia { get; set; }
        public Nullable<int> Sim_Prepago { get; set; }
        public string Sim_Plan { get; set; }
    }
}
