//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models.EFConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SubProyecto
    {
        public int Id { get; set; }
        public Nullable<int> Proyecto { get; set; }
        public string Contrato { get; set; }
        public string SubProyecto { get; set; }
        public Nullable<int> Num { get; set; }
        public string Clave { get; set; }
    }
}
