//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models.EFConn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SEICEntities : DbContext
    {
        public SEICEntities()
            : base("name=SEICEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Area> C_Area { get; set; }
        public virtual DbSet<C_Banco> C_Banco { get; set; }
        public virtual DbSet<C_Celulares> C_Celulares { get; set; }
        public virtual DbSet<C_Credito> C_Credito { get; set; }
        public virtual DbSet<C_Dias> C_Dias { get; set; }
        public virtual DbSet<C_Documentos> C_Documentos { get; set; }
        public virtual DbSet<C_Edificio> C_Edificio { get; set; }
        public virtual DbSet<C_Ejecutivo> C_Ejecutivo { get; set; }
        public virtual DbSet<C_EjecutivoE> C_EjecutivoE { get; set; }
        public virtual DbSet<C_Empresa> C_Empresa { get; set; }
        public virtual DbSet<C_Equipo> C_Equipo { get; set; }
        public virtual DbSet<C_Estado> C_Estado { get; set; }
        public virtual DbSet<C_Estatus> C_Estatus { get; set; }
        public virtual DbSet<C_Estudios> C_Estudios { get; set; }
        public virtual DbSet<C_Jornada> C_Jornada { get; set; }
        public virtual DbSet<C_Modalidad> C_Modalidad { get; set; }
        public virtual DbSet<C_Modulos> C_Modulos { get; set; }
        public virtual DbSet<C_Motivos_B> C_Motivos_B { get; set; }
        public virtual DbSet<C_Municipios> C_Municipios { get; set; }
        public virtual DbSet<C_NOMINAS> C_NOMINAS { get; set; }
        public virtual DbSet<C_Pais> C_Pais { get; set; }
        public virtual DbSet<C_Procesos> C_Procesos { get; set; }
        public virtual DbSet<C_Proyecto> C_Proyecto { get; set; }
        public virtual DbSet<C_ProyectoN> C_ProyectoN { get; set; }
        public virtual DbSet<C_Puesto> C_Puesto { get; set; }
        public virtual DbSet<C_Rechazos_B> C_Rechazos_B { get; set; }
        public virtual DbSet<C_Servicio> C_Servicio { get; set; }
        public virtual DbSet<C_ServicioA> C_ServicioA { get; set; }
        public virtual DbSet<C_SIM> C_SIM { get; set; }
        public virtual DbSet<C_SubProyecto> C_SubProyecto { get; set; }
        public virtual DbSet<C_Tipo> C_Tipo { get; set; }
        public virtual DbSet<C_TipoNomi> C_TipoNomi { get; set; }
        public virtual DbSet<C_Turno> C_Turno { get; set; }
        public virtual DbSet<Cat_Unidad> Cat_Unidad { get; set; }
        public virtual DbSet<R_Edi_Emp> R_Edi_Emp { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T_Alta_imss> T_Alta_imss { get; set; }
        public virtual DbSet<T_Asistencias> T_Asistencias { get; set; }
        public virtual DbSet<T_Asistenciasb> T_Asistenciasb { get; set; }
        public virtual DbSet<T_CExpediente> T_CExpediente { get; set; }
        public virtual DbSet<T_Cimss> T_Cimss { get; set; }
        public virtual DbSet<T_Cip> T_Cip { get; set; }
        public virtual DbSet<T_ClaveInterB> T_ClaveInterB { get; set; }
        public virtual DbSet<T_Comen_Inb> T_Comen_Inb { get; set; }
        public virtual DbSet<T_Cuip> T_Cuip { get; set; }
        public virtual DbSet<T_Curp> T_Curp { get; set; }
        public virtual DbSet<T_DatosBan> T_DatosBan { get; set; }
        public virtual DbSet<T_DatosPersonales> T_DatosPersonales { get; set; }
        public virtual DbSet<T_Dias> T_Dias { get; set; }
        public virtual DbSet<T_Direccion> T_Direccion { get; set; }
        public virtual DbSet<T_DireccionO> T_DireccionO { get; set; }
        public virtual DbSet<T_Eestudios> T_Eestudios { get; set; }
        public virtual DbSet<T_EF> T_EF { get; set; }
        public virtual DbSet<T_Ejecutivo> T_Ejecutivo { get; set; }
        public virtual DbSet<T_Emp_Cre> T_Emp_Cre { get; set; }
        public virtual DbSet<T_Empleado> T_Empleado { get; set; }
        public virtual DbSet<T_EquipoAsignado> T_EquipoAsignado { get; set; }
        public virtual DbSet<T_Expediente> T_Expediente { get; set; }
        public virtual DbSet<T_FActa> T_FActa { get; set; }
        public virtual DbSet<t_FAnteLab> t_FAnteLab { get; set; }
        public virtual DbSet<t_FAntePen> t_FAntePen { get; set; }
        public virtual DbSet<T_FAtec> T_FAtec { get; set; }
        public virtual DbSet<T_Fatigas_Inb> T_Fatigas_Inb { get; set; }
        public virtual DbSet<T_FCartilla> T_FCartilla { get; set; }
        public virtual DbSet<t_Fcedula> t_Fcedula { get; set; }
        public virtual DbSet<T_FCertificado> T_FCertificado { get; set; }
        public virtual DbSet<t_FCip> t_FCip { get; set; }
        public virtual DbSet<t_Fcontrato> t_Fcontrato { get; set; }
        public virtual DbSet<t_FCurp> t_FCurp { get; set; }
        public virtual DbSet<t_FDomicilio> t_FDomicilio { get; set; }
        public virtual DbSet<T_FE> T_FE { get; set; }
        public virtual DbSet<T_Fechas> T_Fechas { get; set; }
        public virtual DbSet<t_FEstudios> t_FEstudios { get; set; }
        public virtual DbSet<t_FExam> t_FExam { get; set; }
        public virtual DbSet<t_FExpediente> t_FExpediente { get; set; }
        public virtual DbSet<T_Fimss> T_Fimss { get; set; }
        public virtual DbSet<T_FimssA> T_FimssA { get; set; }
        public virtual DbSet<T_FIne> T_FIne { get; set; }
        public virtual DbSet<T_Foto> T_Foto { get; set; }
        public virtual DbSet<t_Frfc> t_Frfc { get; set; }
        public virtual DbSet<T_HE> T_HE { get; set; }
        public virtual DbSet<T_HistoriaSA> T_HistoriaSA { get; set; }
        public virtual DbSet<T_Horario> T_Horario { get; set; }
        public virtual DbSet<T_IdAsistencia> T_IdAsistencia { get; set; }
        public virtual DbSet<T_Jornada> T_Jornada { get; set; }
        public virtual DbSet<T_M_Estatus> T_M_Estatus { get; set; }
        public virtual DbSet<T_Matricula> T_Matricula { get; set; }
        public virtual DbSet<T_Modalidad> T_Modalidad { get; set; }
        public virtual DbSet<T_ModeloA> T_ModeloA { get; set; }
        public virtual DbSet<T_NN> T_NN { get; set; }
        public virtual DbSet<T_Nss> T_Nss { get; set; }
        public virtual DbSet<T_PagosExt> T_PagosExt { get; set; }
        public virtual DbSet<T_Privilegios> T_Privilegios { get; set; }
        public virtual DbSet<T_Proyecto> T_Proyecto { get; set; }
        public virtual DbSet<T_ProyEje> T_ProyEje { get; set; }
        public virtual DbSet<T_ProyEje_En> T_ProyEje_En { get; set; }
        public virtual DbSet<T_Rfc> T_Rfc { get; set; }
        public virtual DbSet<T_Servicio> T_Servicio { get; set; }
        public virtual DbSet<T_SubProyecto> T_SubProyecto { get; set; }
        public virtual DbSet<T_Sueldo> T_Sueldo { get; set; }
        public virtual DbSet<T_Telefono> T_Telefono { get; set; }
        public virtual DbSet<t_TipoNomina> t_TipoNomina { get; set; }
        public virtual DbSet<T_Tramites> T_Tramites { get; set; }
        public virtual DbSet<T_Turno> T_Turno { get; set; }
        public virtual DbSet<Tb_Log> Tb_Log { get; set; }
        public virtual DbSet<Tb_Solicitudes> Tb_Solicitudes { get; set; }
        public virtual DbSet<Tb_Usuarios> Tb_Usuarios { get; set; }
        public virtual DbSet<Tb_Usuarios_I> Tb_Usuarios_I { get; set; }
        public virtual DbSet<C_ServicioA_RES> C_ServicioA_RES { get; set; }
        public virtual DbSet<C_ServicioAR> C_ServicioAR { get; set; }
        public virtual DbSet<R_Cel_Sim_Emp> R_Cel_Sim_Emp { get; set; }
        public virtual DbSet<t_reclutamiento> t_reclutamiento { get; set; }
        public virtual DbSet<T_Vacaciones> T_Vacaciones { get; set; }
        public virtual DbSet<tb_empleados_reclutados> tb_empleados_reclutados { get; set; }
        public virtual DbSet<TB_usuarios_portal> TB_usuarios_portal { get; set; }
    }
}
