//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models.EFConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Cel_Sim_Emp
    {
        public int ID_Cel_Sim_Emp { get; set; }
        public string ID_Empleado { get; set; }
        public string Id_Cel { get; set; }
        public string id_Sim { get; set; }
    }
}
