//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models.EFConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Edi_Emp
    {
        public int Id_Edi_Emp { get; set; }
        public Nullable<int> Id_Edificio { get; set; }
        public Nullable<int> Num_Empleado { get; set; }
    }
}
