//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models.EFConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Asistenciasb
    {
        public int Id { get; set; }
        public string Num_empleado { get; set; }
        public string Num_Asistencia { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Incidencia { get; set; }
        public Nullable<int> Dia { get; set; }
        public Nullable<int> Proyecto { get; set; }
        public Nullable<int> SubProyecto { get; set; }
        public Nullable<int> Servicio { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> id_cf { get; set; }
    }
}
