//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models.EFConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Direccion
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Num_Empleado { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string CP { get; set; }
        public Nullable<int> Pais { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Municipio { get; set; }
    }
}
