//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models.EFConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Fimss
    {
        public int Id { get; set; }
        public string Num_Empleado { get; set; }
        public string Foja_A { get; set; }
        public string Archivo { get; set; }
        public Nullable<int> Solicitud { get; set; }
    }
}
