//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Celulares
    {
        public int ID_Cel { get; set; }
        public string Cel_Modelo { get; set; }
        public string Cel_Marca { get; set; }
        public Nullable<System.DateTime> Cel_FechaCompra { get; set; }
        public string Cel_Proveedor { get; set; }
        public string Cel_Imei { get; set; }
        public Nullable<int> Cel_Liberado { get; set; }
    }
}
