//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Documentos
    {
        public int Id { get; set; }
        public Nullable<int> Documento { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
