//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Municipios
    {
        public int Id { get; set; }
        public Nullable<int> Id_Estado { get; set; }
        public string Municipio { get; set; }
    
        public virtual C_Estado C_Estado { get; set; }
    }
}
