//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CExpediente
    {
        public int Id { get; set; }
        public string Num_Empleado { get; set; }
        public string Acta_O { get; set; }
        public string Acta_C { get; set; }
        public string Cest_O { get; set; }
        public string Cest_C { get; set; }
        public string Cartilla_O { get; set; }
        public string Cartilla_C { get; set; }
        public string Cdomi_O { get; set; }
        public string Cdomi_C { get; set; }
        public string Cine_O { get; set; }
        public string Cine_C { get; set; }
        public string Curp_O { get; set; }
        public string Curp_C { get; set; }
        public string Rfc_O { get; set; }
        public string Rfc_C { get; set; }
        public string Imss_O { get; set; }
        public string Imss_C { get; set; }
        public string Cante_O { get; set; }
        public string Cante_C { get; set; }
        public string Clabo_O { get; set; }
        public string Clabo_C { get; set; }
        public string Exa_O { get; set; }
        public string Exa_C { get; set; }
        public string Cont_O { get; set; }
        public string Cont_C { get; set; }
        public string Ced_O { get; set; }
        public string Ced_C { get; set; }
        public string Comentarios { get; set; }
    }
}
