//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Tramites
    {
        public int Id { get; set; }
        public string Num_Empleado { get; set; }
        public string VolanteC { get; set; }
        public Nullable<System.DateTime> FechaIC { get; set; }
        public Nullable<System.DateTime> FechaRC { get; set; }
        public string VolanteI { get; set; }
        public Nullable<System.DateTime> FechaII { get; set; }
        public Nullable<System.DateTime> FechaRI { get; set; }
        public string VolanteCR { get; set; }
        public Nullable<System.DateTime> FechaICR { get; set; }
        public Nullable<System.DateTime> FechaRCR { get; set; }
        public string Opinion { get; set; }
        public string CUIP { get; set; }
        public string Matri { get; set; }
        public string Activo { get; set; }
        public string Expediente { get; set; }
        public string Observaciones { get; set; }
    }
}
