//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Solicitudes
    {
        public int Id { get; set; }
        public string Num_Empleado { get; set; }
        public Nullable<int> Proceso { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Afecto { get; set; }
        public string ComentarioS { get; set; }
        public Nullable<System.DateTime> FechaR { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> Motivo { get; set; }
        public Nullable<int> Proyecto { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Subproyecto { get; set; }
        public Nullable<int> Servicio { get; set; }
    }
}
