//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modulosASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_usuarios_portal
    {
        public int Id { get; set; }
        public string Num_Empleado { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string Correo { get; set; }
    }
}
