<?xml version="1.0" encoding="utf-8"?><Database Name="SEIC" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-DVRD5GT\SQLEXPRESS01;Initial Catalog=SEIC;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SEICConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.C_Ejecutivo" Member="C_Ejecutivo">
    <Type Name="C_Ejecutivo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ejecutivo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Num_Empleado" Type="System.String" DbType="NChar(6)" CanBeNull="true" />
    </Type>
  </Table>
</Database>